# NumPy Array'i Oluşturmak

In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
a = np.array([1,2,3,4,5])

In [4]:
type(a)

numpy.ndarray

In [7]:
np.array([3.14, 4, 13, 2], dtype = "int")

array([ 3,  4, 13,  2])

In [8]:
# sifirdan array oluşturma

In [9]:
np.zeros(10, dtype = "int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.ones((3,5), dtype = "int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [13]:
np.full((3,5), 3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [14]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [15]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [17]:
np.random.normal(10, 4,(3,4))

array([[ 3.25077825,  4.07933496, 10.5266305 , 13.96179889],
       [ 9.14919842,  3.59880887, 10.50638827,  9.77327767],
       [10.27497314,  8.55682794,  9.00778077,  6.43328171]])

In [18]:
np.random.randint(0, 10, (3,3))

array([[0, 4, 6],
       [3, 6, 7],
       [9, 4, 8]])