# Yeniden Şekillendirme (reshaping)

In [1]:
import numpy as np

In [2]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
a = np.arange(1,10)

In [5]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a.ndim

1

In [9]:
b = a.reshape((1,9))

In [10]:
b.ndim

2