# Array Sıralama (sorting)

In [2]:
import numpy as np

In [3]:
v = np.array([2,1,4,3,5])

In [4]:
v

array([2, 1, 4, 3, 5])

In [5]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [6]:
v

array([2, 1, 4, 3, 5])

In [7]:
v.sort()

In [8]:
v

array([1, 2, 3, 4, 5])

In [9]:
# iki boyutlu

In [12]:
m = np.random.normal(20,5, (3,3))

In [13]:
m

array([[14.50142027, 28.08827625, 15.76254699],
       [22.18058283, 24.16248176, 19.65311637],
       [15.30028864, 30.52779186, 16.65039398]])

In [14]:
np.sort(m, axis = 1)

array([[14.50142027, 15.76254699, 28.08827625],
       [19.65311637, 22.18058283, 24.16248176],
       [15.30028864, 16.65039398, 30.52779186]])

In [15]:
np.sort(m, axis = 0)

array([[14.50142027, 24.16248176, 15.76254699],
       [15.30028864, 28.08827625, 16.65039398],
       [22.18058283, 30.52779186, 19.65311637]])