# Array Birleştirme (concatenation)

In [2]:
import numpy as np

In [3]:
x = np.array([1,2,3])

In [4]:
y = np.array([4,5,6])

In [6]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [7]:
z = np.array([7,8,9])

In [9]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# iki boyut

In [11]:
a = np.array([[1,2,3], 
              [4,5,6]])

In [12]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [13]:
np.concatenate([a,a], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])