# Index ile Elemanlara Erişmek

In [1]:
import numpy as np

In [2]:
a = np.random.randint(10, size = 10)

In [3]:
a

array([1, 5, 2, 7, 5, 5, 6, 8, 6, 5])

In [4]:
a[0]

1

In [5]:
a[-1]

5

In [6]:
a[0] = 100

In [7]:
a

array([100,   5,   2,   7,   5,   5,   6,   8,   6,   5])

In [9]:
m = np.random.randint(10, size = (3,5))

In [10]:
m

array([[6, 6, 6, 8, 4],
       [3, 8, 5, 6, 4],
       [3, 5, 4, 1, 0]])

In [11]:
m[0,0]

6

In [12]:
m[1,1]

8

In [13]:
m[1,4]

4

In [14]:
m[1,4] = 99

In [15]:
m

array([[ 6,  6,  6,  8,  4],
       [ 3,  8,  5,  6, 99],
       [ 3,  5,  4,  1,  0]])

In [16]:
m[1,4] = 2.2

In [17]:
m

array([[6, 6, 6, 8, 4],
       [3, 8, 5, 6, 2],
       [3, 5, 4, 1, 0]])