# Slicing ile Elemanlara Erişmek (Array Alt kümesine Erişmek)

In [1]:
import numpy as np

In [2]:
a = np.arange(20,30)

In [3]:
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [4]:
a[0:3]

array([20, 21, 22])

In [5]:
a[:3]

array([20, 21, 22])

In [6]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [7]:
a[1::2]

array([21, 23, 25, 27, 29])

In [8]:
a[0::2]

array([20, 22, 24, 26, 28])

In [9]:
a[2::2]

array([22, 24, 26, 28])

In [10]:
a[0::3]

array([20, 23, 26, 29])

In [11]:
# iki boyutlu slice işlemleri

In [12]:
m = np.random.randint(10, size = (5,5))

In [13]:
m

array([[9, 4, 3, 3, 0],
       [8, 9, 2, 5, 8],
       [0, 0, 5, 9, 8],
       [5, 3, 5, 7, 1],
       [3, 2, 8, 8, 0]])

In [14]:
m[:,0]

array([9, 8, 0, 5, 3])

In [15]:
m[:,1]

array([4, 9, 0, 3, 2])

In [16]:
m[:,4]

array([0, 8, 8, 1, 0])

In [17]:
m[0,:]

array([9, 4, 3, 3, 0])

In [18]:
m[0]

array([9, 4, 3, 3, 0])

In [19]:
m[1,:]

array([8, 9, 2, 5, 8])

In [20]:
m[0:2, 0:3]

array([[9, 4, 3],
       [8, 9, 2]])

In [22]:
m[:: , 0:2]

array([[9, 4],
       [8, 9],
       [0, 0],
       [5, 3],
       [3, 2]])

In [23]:
m[1:3, 0:2 ]

array([[8, 9],
       [0, 0]])