# Alt Küme Üzerinde İşlem Yapma 

In [1]:
import numpy as np

In [2]:
a = np.random.randint(10, size = (5,5))

In [3]:
a

array([[8, 3, 5, 7, 2],
       [4, 0, 0, 4, 0],
       [5, 1, 1, 3, 5],
       [0, 4, 8, 6, 1],
       [1, 4, 4, 3, 5]])

In [4]:
alt_a = a[0:3, 0:2]

In [5]:
alt_a

array([[8, 3],
       [4, 0],
       [5, 1]])

In [6]:
alt_a[0,0] = 99999

In [7]:
alt_a[1,1] = 888

In [8]:
alt_a

array([[99999,     3],
       [    4,   888],
       [    5,     1]])

In [9]:
a

array([[99999,     3,     5,     7,     2],
       [    4,   888,     0,     4,     0],
       [    5,     1,     1,     3,     5],
       [    0,     4,     8,     6,     1],
       [    1,     4,     4,     3,     5]])

In [10]:
m = np.random.randint(10, size = (5,5))

In [11]:
m

array([[6, 2, 2, 9, 5],
       [2, 7, 1, 0, 5],
       [4, 8, 8, 9, 1],
       [0, 5, 4, 5, 0],
       [3, 1, 0, 0, 6]])

In [12]:
alt_b = m[0:3, 0:2].copy()

In [13]:
alt_b

array([[6, 2],
       [2, 7],
       [4, 8]])

In [14]:
alt_b[0,0] = 9999

In [15]:
alt_b

array([[9999,    2],
       [   2,    7],
       [   4,    8]])

In [16]:
m

array([[6, 2, 2, 9, 5],
       [2, 7, 1, 0, 5],
       [4, 8, 8, 9, 1],
       [0, 5, 4, 5, 0],
       [3, 1, 0, 0, 6]])